### PR TITLE
Add DEBUG and NOTICE severities

### PR DESCRIPTION
**Pull request by b0d0nne11**
I have some logging in a different program that I would like to move from `INFO` to `DEBUG` or `NOTICE`. This PR allows that by adding the those severities.

### CODE REVIEW

**Comment by ralphm** [comment]
While I appreciate that you are adding the `DEBUG` level, and know that `NOTICE` exists in syslog, what is the benefit of having the latter?

So far, we haven't used the `NOTICE` level in Mailgun code, as far as I know, and I want to note that this level doesn't exist in the Python Logging Facility. Semantically it doesn't seem much different from `INFO`.

**Comment by b0d0nne11** [comment]
So I don't specifically require it ATM but it was easy to add at the same time and I've worked with other products that use it and have liked it. Its meant for entries that people should pay attention to but aren't technically errors. An example of this might be something like connection reset. I want to know that it happened but by itself ifs not really an error condition and the program just deals with it.

**Comment by ralphm** [comment]
Right, I'm sure we could use the level, but given that Python apps can't express it, I'd like to suggest to keep with the common denominator. I also don't think in practice we are very consistent in the use of levels (yet?) and adding one to the mix doesn't seem helpful at this point. YMMV.

For completeness, Python also doesn't have `ALERT` or `EMERG`.

**Comment by b0d0nne11** [comment]
Make sense and I don't have that strong of an opinion about it. I dropped the `NOTICE` level support out of the PR. Maybe we can revisit it at a latter time if there is a stronger use case.

**Comment by ralphm** [comment]
👍

**Comment by r0mant** [comment]
lgtm

**Pull request merged**
